### ISSUE TITLE
Is there any way to get the spec as json without calling doc/api.json? 

### ISSUE THREAD

**Issue by kkivan** [SMILEY4/ktor-openapi-tools#119]

**Comment by SMILEY4** [comment]
Hi,
you can get the json-string from `ApiSpec.get(PluginConfigDsl.DEFAULT_SPEC_ID)` after its built by its id. By default, i.e. if you are not using multiple specs and the default configuration, the id is always `PluginConfigDsl.DEFAULT_SPEC_ID`, otherwise the one you assigned.
Another option is the "post-build"-hook in the plugin config that is called with the finished OpenAPI-object.
```kotlin
install(SwaggerUi) {
   postBuild = { openApiSpec ->
      // ...
   }
}
```
