### ISSUE TITLE
Allow multiple security schemes for a route

### ISSUE THREAD

**Issue by aleksa-djurdjulov** [SMILEY4/ktor-openapi-tools#31]
OAS3 allows combining security requirements with logical operators (OR and AND). More details can be found in the [documentation](https://swagger.io/docs/specification/authentication/) under _Using Multiple Authentication Types_, but the basic logic for documenting security of a route is as follow:
```
security:    # A OR B
  - A
  - B
```
```
security:    # A AND B
  - A
    B
```
```
security:    # (A AND B) OR (C AND D)
  - A
    B
  - C
    D
```

From my observation of this library, this should be doable by changing the `OpenApiRoute.securitySchemeName` ([link](https://github.com/SMILEY4/ktor-swagger-ui/blob/develop/src/main/kotlin/io/github/smiley4/ktorswaggerui/dsl/OpenApiRoute.kt#L39)) from a `String?` to something like a `Collection<Collection<String>>` (or just `Collection<String>` for start, to support the OR logical operator) and supporting the following change [here](https://github.com/SMILEY4/ktor-swagger-ui/blob/develop/src/main/kotlin/io/github/smiley4/ktorswaggerui/specbuilder/OApiPathBuilder.kt#L45).

**Comment by SMILEY4** [comment]
Hi, thanks for the suggestion.
I added the possibility to specify a collection of strings / security scheme names in version [1.3.0](https://github.com/SMILEY4/ktor-swagger-ui/releases/tag/1.3.0). Currently, all specified names are handled via an "or"-operator, since imho this is the most common case.
- `OpenApiRoute.securitySchemeName` still works as expected
- `OpenApiRoute.securitySchemeNames` to specify a collection of names
- same for the default security scheme name(s)
