### ISSUE TITLE
 Is it possible to use SerialName in data class fields?

### ISSUE THREAD

**Issue by pdrozz** [SMILEY4/ktor-openapi-tools#48]
Is there any way to use a kotlinx.serialization or gson annotation on the fields of a data class in the version 1.6.1? 

For example, I'm using the code below, but the generated example response is picking the data class field name and ignoring the annotation:

```kotlin
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class Pet(
   @SerialName("first_name") 
   val firstName: String
)

get("pet", {
    response {
        HttpStatusCode.Ok to {
            body<Pet>() {
               mediaType(ContentType.Application.Json)
               example(
                   name = "get pet name",
                   value = Pet("Max")
              )
            }
        }
    }
}) {
    // handle request...
}
```

But the generated example give me:
``` json
{
    "firstName": "Max"
}
```

instead
``` json
{
    "first_name": "Max"
}
``` 

I saw that in the 2.0.0 version will be possible to set a custom example encoding

**Comment by SMILEY4** [comment]
Hi,
there is [this](https://github.com/SMILEY4/ktor-swagger-ui/issues/46#issuecomment-1556953476) workaround for using kotlinx for schemas. For examples it is possible to set the value to a json-string provided by kotlinx instead of an object.

Version 2.x will have a much simpler/cleaner way of replacing the default encoders with e.g. kotlinx and should be done/release in a few days. If you want you could also check out the latest release candidate.
