### ISSUE TITLE
Support for Rate Limiter

### ISSUE THREAD

**Issue by x2d7751347m** [SMILEY4/ktor-openapi-tools#63]
Here is the rate limiter: https://ktor.io/docs/rate-limit.html

I tried it below
``
routing {
       rateLimit {
                    get("/something", {
                        summary = "something Endpoint."
                        response {
....
``

Result
![image](https://github.com/SMILEY4/ktor-swagger-ui/assets/62936128/b72faf3f-d39b-4b08-bf1f-753e7dfd59c4)

URL paths are affected by the rateLimit function.

Are there any plans to support the rate limiter?

**Comment by SMILEY4** [comment]
Hi,
there is no plan to directly "support" rate limiter or other plugins for this exact use-case, however, this issue can easily be fixed by adding the rate-limiter-part of the route to a list of ignored parts (PluginConfig#ignoredRouteSelectors). See https://github.com/SMILEY4/ktor-swagger-ui/issues/43 for more information.
